In [240]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.metrics import confusion_matrix
from sklearn.utils import shuffle

In [241]:
df = pd.read_csv("water_potability.csv")
# df = shuffle(df, random_state=0)
y = df['Potability']
x = df.drop(['Potability','Sulfate','Organic_carbon','Conductivity', 'Chloramines', 'Trihalomethanes'],axis='columns')
df.head(20)

ph    Hardness        Solids  Chloramines     Sulfate  \
0         NaN  204.890455  20791.318981     7.300212  368.516441   
1    3.716080  129.422921  18630.057858     6.635246         NaN   
2    8.099124  224.236259  19909.541732     9.275884         NaN   
3    8.316766  214.373394  22018.417441     8.059332  356.886136   
4    9.092223  181.101509  17978.986339     6.546600  310.135738   
5    5.584087  188.313324  28748.687739     7.544869  326.678363   
6   10.223862  248.071735  28749.716544     7.513408  393.663396   
7    8.635849  203.361523  13672.091764     4.563009  303.309771   
8         NaN  118.988579  14285.583854     7.804174  268.646941   
9   11.180284  227.231469  25484.508491     9.077200  404.041635   
10   7.360640  165.520797  32452.614409     7.550701  326.624353   
11   7.974522  218.693300  18767.656682     8.110385         NaN   
12   7.119824  156.704993  18730.813653     3.606036  282.344050   
13        NaN  150.174923  27331.361962     6.838223  299.415781   
14   7.496232  205.344982  28388.004887     5.072558         NaN   
15   6.347272  186.732881  41065.234765     9.629596  364.487687   
16   7.051786  211.049406  30980.600787    10.094796         NaN   
17   9.181560  273.813807  24041.326280     6.904990  398.350517   
18   8.975464  279.357167  19460.398131     6.204321         NaN   
19   7.371050  214.496610  25630.320037     4.432669  335.754439   

    Conductivity  Organic_carbon  Trihalomethanes  Turbidity  Potability  
0     564.308654       10.379783        86.990970   2.963135           0  
1     592.885359       15.180013        56.329076   4.500656           0  
2     418.606213       16.868637        66.420093   3.055934           0  
3     363.266516       18.436524       100.341674   4.628771           0  
4     398.410813       11.558279        31.997993   4.075075           0  
5     280.467916        8.399735        54.917862   2.559708           0  
6     283.651634       13.789695        84.603556   2.672989           0  
7     474.607645       12.363817        62.798309   4.401425           0  
8     389.375566       12.706049        53.928846   3.595017           0  
9     563.885481       17.927806        71.976601   4.370562           0  
10    425.383419       15.586810        78.740016   3.662292           0  
11    364.098230       14.525746        76.485911   4.011718           0  
12    347.715027       15.929536        79.500778   3.445756           0  
13    379.761835       19.370807        76.509996   4.413974           0  
14    444.645352       13.228311        70.300213   4.777382           0  
15    516.743282       11.539781        75.071617   4.376348           0  
16    315.141267       20.397022        56.651604   4.268429           0  
17    477.974642       13.387341        71.457362   4.503661           0  
18    431.443990       12.888759        63.821237   2.436086           0  
19    469.914551       12.509164        62.797277   2.560299           0

In [242]:
x["ph"] = x["ph"].fillna(int(x['ph'].mean()))
# x["Sulfate"] = x["Sulfate"].fillna(int(x['Sulfate'].mean()))
x["Turbidity"] = x["Turbidity"].fillna(int(x['Turbidity'].mean()))
x["Turbidity"] = x["Turbidity"]/(int(x['Turbidity'].mean()))
# x["Trihalomethanes"] = x["Trihalomethanes"].fillna(int(x['Trihalomethanes'].mean()))
# x["Trihalomethanes"] = x["Trihalomethanes"]/(int(x['Trihalomethanes'].mean()))
# x["Organic_carbon"] = x["Organic_carbon"].fillna(int(x['Organic_carbon'].mean()))
# x["Organic_carbon"] = x["Organic_carbon"]/(int(x['Organic_carbon'].mean()))
# x["Conductivity"] = x["Conductivity"].fillna(int(x['Conductivity'].mean()))
# x["Conductivity"] = x["Conductivity"]/(int(x['Conductivity'].mean()))
# x["Chloramines"] = x["Chloramines"].fillna(int(x['Chloramines'].mean()))
# x["Chloramines"] = x["Chloramines"]/(int(x['Chloramines'].mean()))
x["Solids"] = x["Solids"].fillna(int(x['Solids'].mean()))
x["Solids"] = x["Solids"]/(int(x['Solids'].mean()))
x["Hardness"] = x["Hardness"].fillna(int(x['Hardness'].mean()))
x["Hardness"] = x["Hardness"]/(int(x['Hardness'].mean()))
x.head(20)

ph  Hardness    Solids  Turbidity
0    7.000000  1.045359  0.944459   0.987712
1    3.716080  0.660321  0.846282   1.500219
2    8.099124  1.144063  0.904404   1.018645
3    8.316766  1.093742  1.000201   1.542924
4    9.092223  0.923987  0.816707   1.358358
5    5.584087  0.960782  1.305927   0.853236
6   10.223862  1.265672  1.305974   0.890996
7    8.635849  1.037559  0.621063   1.467142
8    7.000000  0.607085  0.648932   1.198339
9   11.180284  1.159344  1.157650   1.456854
10   7.360640  0.844494  1.474181   1.220764
11   7.974522  1.115782  0.852533   1.337239
12   7.119824  0.799515  0.850859   1.148585
13   7.000000  0.766199  1.241545   1.471325
14   7.496232  1.047678  1.289543   1.592461
15   6.347272  0.952719  1.865414   1.458783
16   7.051786  1.076783  1.407314   1.422810
17   9.181560  1.397009  1.092093   1.501220
18   8.975464  1.425292  0.884001   0.812029
19   7.371050  1.094370  1.164274   0.853433

In [243]:
x.describe()

ph     Hardness       Solids    Turbidity
count  3276.000000  3276.000000  3276.000000  3276.000000
mean      7.068685     1.001885     1.000004     1.322262
std       1.470239     0.167754     0.398318     0.260127
min       0.000000     0.242000     0.014579     0.483333
25%       6.277673     0.902299     0.711669     1.146570
50%       7.000000     1.004937     0.950660     1.318343
75%       7.870050     1.105446     1.241608     1.500107
max      14.000000     1.648592     2.781284     2.246333

In [244]:
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.3)
model=LogisticRegression()
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
print(model.coef_)
print(model.intercept_)

[[-2.38172618e-05  2.14785129e-03  4.16863337e-02 -9.49007114e-02]]
[-0.30622409]


In [245]:
print(metrics.accuracy_score(y_test,y_pred))

0.6429298067141404


In [246]:
cm=np.array(confusion_matrix(y_test,y_pred))
print(cm)

[[632   0]
 [351   0]]


# Support Vector Machine Classification implementation:

In [247]:
clf=SVC()
#Training of the model 
clf.fit(X_train,y_train)
#Testing of our trained model 
pred=clf.predict(X_test)

In [248]:
print(metrics.accuracy_score(y_test,pred))
#Importing confusion matrix
confusionm=np.array(confusion_matrix(y_test,pred))
print(confusionm)

0.6429298067141404
[[632   0]
 [351   0]]


# Naive Bayes Classification implementation:

In [249]:
classifier = GaussianNB()
classifier.fit(X_train, y_train)
y_pred_ = classifier.predict(X_test)
print(metrics.accuracy_score(y_test,y_pred_))

0.6337741607324516


In [250]:
confusionm=np.array(confusion_matrix(y_test,pred))
print(confusionm)

[[632   0]
 [351   0]]


In [257]:
from sklearn.cluster import KMeans
km = KMeans(n_clusters=2)
km.fit(x)
print(km.cluster_centers_)
print(km.labels_)
y_pred1 = pd.Series(km.labels_)
y_pred1.head(20)
confusionm=np.array(confusion_matrix(y,y_pred1))
print(confusionm)
print("Accuracy",accuracy_score(y_test,y_pred))

[[6.28557284 0.99292466 1.01376677 1.33209573]
 [8.58644825 1.01925172 0.97333074 1.30320326]]
[0 0 1 ... 1 0 1]
[[1311  687]
 [ 851  427]]


In [252]:
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.25, random_state=0)  
from sklearn.preprocessing import StandardScaler    
st= StandardScaler()    
x_train= st.fit_transform(x_train,y_train)    
x_test= st.transform(x_test)
from sklearn.neighbors import KNeighborsClassifier  
#minkowski is like eucledian only a way to find distance between two points
knn= KNeighborsClassifier(n_neighbors=8, metric='minkowski', p=5 )  
knn.fit(x_train, y_train)
y_pred=knn.predict(x_test)  
from sklearn import metrics 
from sklearn.metrics import accuracy_score
print("Accuracy",accuracy_score(y_test,y_pred))
cm= confusion_matrix(y_test, y_pred)  
print(cm)

Accuracy 0.5836385836385837
[[409  93]
 [248  69]]
